[AppSettings]
LogLevel=DEBUG
LogFileQuotaKbyte=1024
LogFileSplits=3
LogFilePath=/log/charx-ocpp16-agent/charx-ocpp16-agent.log

[DatabaseParameters]
DatabaseFilePath=/data/charx-ocpp16-agent/ocpp16.db

[MqttParameters]
Host=127.0.0.1
Port=1883
ClientId=charx-ocpp16-agent
User=
Password=

[OcppParameters]
BackendURL=wss://phoenixcontact.com:8080/websocket/CentralSystemService/ChargeBox_42
Interface=eth0
ChargeBoxID=ChargeBox_42
ChargeBoxSerialNumber=123456
ChargePointModel=Phoenix_Contact_M1
ChargePointSerialNumber=123456
ChargePointVendor=Phoenix_Contact
MeterSerialNumber=12345678
MeterType=Meter_type_A
ServiceRestart=False
ServiceUID=12341234
FreeMode=False
FreeModeUID=43214321

[JupiCoreParameters]
Host=127.0.0.1
Port=5555

[RESTParameters]
Host=0.0.0.0
Port=2106
