[AppSettings]
LogLevel=DEBUG
LogFileQuotaKbyte=1024
LogFileSplits=3
LogFilePath=/log/charx-modbus-server/charx-modbus-server.log
KeepAliveIntervalSec=5

[DevicesParameters]
DevicesFolderPath=/data/charx-modbus-agent/devices/

[MqttParameters]
Host=127.0.0.1
Port=1883
ClientId=charx-modbus-agent
KeepAlive=60
User=
Password=

[RestParameters]
Host=0.0.0.0
Port=9502
