[AppSettings]
LogLevel=INFO
LogFileQuotaKbyte=1024
LogFileSplits=3
LogFilePath=/log/charx-jupicore/charx-jupicore.log
KeepAliveIntervalSec=5

[DatabaseParameters]
DatabaseFilePath=/data/charx-jupicore/jupicore.db
RfidWhiteListLimit=500

[RestApi]
Host=0.0.0.0
Port=5555

[MqttParameters]
Host=127.0.0.1
Port=1883
ClientId=charx-jupicore
KeepAlive=60
User=
Password=
DefaultPublishQoS=0
CriticalPublishQoS=0

[ControllerAgent]
ReStart=True
Host=127.0.0.1
Port=4444
HeartbeatIntervalSec=5
ConnectionRetrySec=5

[ChargingControllers]
NominalVoltage=230.0
OverTemperatureOhmsMin=100
OverTemperatureOhmsMax=100000
CoordinatedLocking=True
ParallelLockingsPermitted=3
OfflineContractVerificationEnabled=False

[ChargingPoints]
RfidChargeGrantTimeoutSec=60
RfidChargeEnabledBackupUsage=False
MinChargeCurrentLimit=6
MaxChargeCurrentLimit=80
MinChargeCurrentDefault=10
MaxChargeCurrentDefault=16
FallbackChargeCurrentDefault=6
DeratingStartCurrentDefault=16
DeratingStartTemperatureCelciusMin=0
DeratingStartTemperatureCelciusMax=80
DeratingStartTemperatureCelciusDefault=40
DeratingStopCurrentDefault=10
DeratingStopTemperatureCelciusMin=40
DeratingStopTemperatureCelciusMax=100
DeratingStopTemperatureCelciusDefault=60

[Datetime]
tz=Europe/Berlin

