[AppSettings]
LogLevel=INFO
LogFileQuotaKbyte=2048
LogFileSplits=3
LogFilePath=/log/charx-loadmanagement-agent/charx-loadmanagement-agent.log

[MqttParameters]
Host=127.0.0.1
Port=1883
ClientId=charx-loadmanagement-agent
KeepAlive=5
User=
Password=

[RESTParameters]
Host=127.0.0.1
Port=5555

[LMGTRESTParameters]
Host=0.0.0.0
Port=1603

[LoadmanagementRestrictionParameters]
MaxCurrentStation=1000
MaxCurrentOffsetForFuse=0
MinCurrentLossForRecalculation=10