[AppSettings]
LogLevel=INFO
LogFileQuotaKbyte=1024
LogFileSplits=3
LogFilePath=/log/charx-website/charx-website.log
KeepAliveIntervalSec=5

[RestApi]
Host=0.0.0.0
Port=5000

[MqttParameters]
Host=127.0.0.1
Port=1883
ClientId=charx-website
KeepAlive=60
User=
Password=

[Folder]
UploadFolder=/data/charx-website/upload/

[DatabaseParameters]
DatabaseFilePath=/data/charx-website/website.db
