[AppSettings]
LogLevel=INFO
LogFileQuotaKbyte=1024
LogFileSplits=3
LogFilePath=/log/charx-modbus-server/charx-modbus-server.log
KeepAliveIntervalSec=5
FtpDownloadHost=192.168.0.1
FtpDownloadUser=user
FtpDownloadPassword=password
FtpDownloadFolder=/folder/
FtpDownloadFile=Sprint20_V0_3_1.raucb
DownloadTargetDirectory=/data/charx-modbus-server/

[APIParameters]
Host=0.0.0.0
Port=9555
ConfigFile=/data/charx-modbus-server/configuration.json

[DevicesParameters]
DevicesFolderPath=/data/charx-modbus-server/
DevicesPollIntervalSec=5

[MqttParameters]
Host=127.0.0.1
Port=1883
ClientId=charx-modbus-server
KeepAlive=60
User=
Password=

[SCMParameters]
Host=127.0.0.1
Port=5001

[ServerParameters]
Host=0.0.0.0
Port=502

[JupicoreParameters]
Host=127.0.0.1
Port=5555
